### ISSUE TITLE
Found that there is an experimental result in the paper that may be very inaccurate.

### ISSUE THREAD

**Issue by fuchun-wang** [iamkanghyunchoi/ait#2]
When i played with ZeroQ codes. I was very surprised to find that the results for ZeroQ/Resnet-18/w4a4/ in Table 1 of the paper are very low, 22.58%. But when I tried to run the official ZeroQ code, the result was **47.96%**. Result for w5a5 setting is 68.26 % compared to 59.6 in the paper.

By the way, your work is solid and impressive!!!

**Comment by iamkanghyunchoi** [comment]
Thank you for being so interested in our paper. 
Right after I read your issue, I newly cloned the original github repo of ZeroQ and ran it again. 
The result is shown below, that of ResNet-18/w4a4, which records 21.79% of top-1 accuracy. 
Would you elaborate your test environment?

![Screen Shot 2022-04-14 at 10 35 17 PM](https://user-images.githubusercontent.com/28946887/163402046-3d804c86-21c7-4522-b326-996dff996c01.png)

**Comment by fuchun-wang** [comment]
<img width="600" alt="截屏2022-04-14 下午10 09 45" src="https://user-images.githubusercontent.com/87461048/163408405-5f1af524-8b9b-4144-982d-1f44c12166c2.png">
<img width="636" alt="截屏2022-04-14 下午10 10 05" src="https://user-images.githubusercontent.com/87461048/163408460-6483a1e1-1321-4d9b-b7b9-994af9279d04.png">

**Comment by fuchun-wang** [comment]
@iamkanghyunchoi  I'm so sorry, I forgot to change something.
Thank u for your quick reply.
Sorry again.

**Comment by iamkanghyunchoi** [comment]
The problem seems to be related to activation bit setting. 
Would you check the activation bit again?

EDIT : Oh, you fixed it. Thank you again for paying attention to our paper!

**Comment by fuchun-wang** [comment]
Yes! You can just close this 'stupid' issue. Sorry for wasting your precious time.
