### ISSUE TITLE
Comparison with previous data-free quantization methods

### ISSUE THREAD

**Issue by DCNSW** [iamkanghyunchoi/ait#3]
Thanks for your good work on data-free quantization and the release of the code.

[Zero-shot adversarial quantization](https://openaccess.thecvf.com/content/CVPR2021/papers/Liu_Zero-Shot_Adversarial_Quantization_CVPR_2021_paper.pdf)(ZAQ) is also a data-free quantization method with adversarial exploration. I notice that both [IntraQ](https://github.com/zysxmu/IntraQ) and [AIT](https://github.com/iamkanghyunchoi/ait) are not compared to the ZAQ method. Are they solving different problems or having different experiment settings?

Thanks for your answer.

**Comment by iamkanghyunchoi** [comment]
First of all, I appreciate your interest in our paper.

I believe that zero-shot quantization and data-free quantization are identical terms that aim at neural network quantization without any training dataset. Therefore, AIT, IntraQ, and ZAQ are trying to solve the same problem.

However, ZAQ uses symmetric quantization for weight and activation, while our method utilizes asymmetric quantization for both. Therefore, it is not suitable to directly compare the paper’s result with our experimental result.

In addition, we were not able to reproduce most of the results from the original ZAQ paper.
